cxx_binary(
  name = '01-to_int',
  srcs = [
    '01-to_int.cpp',
  ],
  deps = [
    '//:optional-lite',
  ],
)

cxx_binary(
  name = '02-nodefltctor',
  srcs = [
    '02-nodefltctor.cpp',
  ],
  deps = [
    '//:optional-lite',
  ],
)

cxx_binary(
  name = '04-any-optional-variant',
  srcs = [
    '04-any-optional-variant.cpp',
  ],
  deps = [
    '//:optional-lite',
  ],
)
